[tool.poetry]
name = "aionexusmods"
version = "0.1.1"
description = ""
authors = ["Greatness7 <Greatness7@gmail.com>"]
include = ["aionexusmods/py.typed"]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7.4"
marshmallow-dataclass = "^8.4.1"
marshmallow = "^3.11.1"
typeguard = "^2.12.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-asyncio = "^0.14.0"
aioresponses = "^0.7.2"
mypy = "^0.812"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
